version: "3"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "19090:9090"
    volumes:
      - $PWD/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-polystat-panel
      - $PWD/grafana/grafana.ini:/usr/local/etc/grafana/grafana.ini
    volumes:
      - $PWD/grafana/data:/var/lib/grafana
      - $PWD/grafana/datasources:/usr/share/grafana/conf/provisioning/datasources