global:
  scrape_timeout: 15s
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    metrics_path: /metrics
    scrape_timeout: 15s
    scrape_interval: 15s
    static_configs:
      - targets:
        - "localhost:9090"
  - job_name: "app"
    metrics_path: /metrics
    scrape_timeout: 15s
    scrape_interval: 15s
    static_configs:
      - targets:
        - "host.docker.internal:8081"